### ISSUE TITLE
Avoid repeating styles when possible

### ISSUE THREAD

**Issue by zannain** [neverland-coder/prj-rev-bwfs-dasmoto#3]
[Dont-Repeat-Yourself](http://deviq.com/don-t-repeat-yourself/). This is an important programming principle. If you find yourself repeating certain styles this is an indication that you can simplify your stylesheet by making use of CSS classes.

Rather than [applying ](https://github.com/neverland-coder/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/index.css#L2-L4) the following styles 3 times. 

```css
  font-family: Helvetica;
  font-size: 100px;
  font-weight: bold;
```
**Alternatives**

1. Using a `body` selector would be more appropriate

```css
body {
    font-family: Helvetica;
    font-size: 100px;
    font-weight: bold;
}
```

2. Creating a style-specific class

```css
.bold {
   font-weight: bold;
 }
```
Now you can give multiple element tags a class attribute of `bold` and they will all receive this common style. This also makes it easy to update this style simultaneously by modifying that once and every element tags with the class attribute of `bold` will be updated. This is in fact how CSS libraries such as [Bootstrap](https://getbootstrap.com/) work. 

3. [Using CSS Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables)

```css
:root {
    --font-size: 1.75rem;
}

#paint {
     font-size: var(--font-size);
}
```
